language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
  - mysql -e "create database IF NOT EXISTS learnanytime;" -uroot

install: travis_retry composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - phpunit --coverage-clover build/logs/clover.xml

before_script:
  - mysql -e "create database IF NOT EXISTS learnanytime;" -uroot

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - travis_retry php vendor/bin/coveralls -v